In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2],[3,4]])

In [7]:
print(b)

[[1 2]
 [3 4]]


In [8]:
c = np.array([1,2,3,4,5],ndmin = 2)

In [9]:
print(c)

[[1 2 3 4 5]]


In [10]:
d = np.array([1,2,3],dtype = complex)

In [11]:
print(d)

[1.+0.j 2.+0.j 3.+0.j]


In [12]:
print(b.T)

[[1 3]
 [2 4]]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
print(type(b))

<class 'numpy.ndarray'>


In [16]:
print(a.dtype)

int32


In [18]:
x = np.zeros(5)

In [19]:
print(x)

[0. 0. 0. 0. 0.]


In [23]:
y = np.zeros((5,) , dtype = np .int)

C:\Users\陈平安\AppData\Local\Temp\ipykernel_10656\3600516357.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.zeros((5,) , dtype = np .int)


In [24]:
print(y)

[0 0 0 0 0]


In [25]:
z = np.zeros((2,2,),dtype = [('x','i4'),('y','i4')])

In [26]:
print(z)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [1]:
import numpy as np
x = np.ones(5)
print(x)
x = np.ones([2,2],dtype=int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [2]:
x = np.diag([1,2,3])
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
a = np.arange(10)
print(a)
a5 = np.arange(1,2,0.1)
print(a5)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [4]:
a = np.linspace(0,1,10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [5]:
a = np.logspace(0,1,5)
print(a)

[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [6]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = a.flatten()
c = a.ravel()
d = a.reshape(-1)
print(a)
print(b)
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [8]:
a = np.array([[1,2,3],[4,5,6]])
b = a.transpose()
c = a.T
d = a.swapaxes(0,1)
e = np.transpose(a,(1,0))
print(a)
print(b)
print(c)
print(d)
print(e)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [9]:
a = np.arange(6).reshape(3,2)
b = a*2
c = np.vstack((a,b))
print(a)
print(b)
print(c)

[[0 1]
 [2 3]
 [4 5]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  2]
 [ 4  6]
 [ 8 10]]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
b = np.arange(2,8).reshape(2,3)
c1 = np.concatenate([a,b],axis=0)
d1 = np.concatenate([a,b],axis=1)
print(a)
print(b)
print(c1)
print(d1)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]


In [11]:
a = np.arange(1,19).reshape(6,3)
b,c = np.split(a,[4],axis=0)
d,e = np.vsplit(a,[4])
print(a)
print(b)
print(c)
print(d)
print(e)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [12]:
a = np.arange(1,13).reshape(2,6)
b,c = np.split(a,[-1],axis=1)
d,e = np.hsplit(a,[-1])
print(a)
print(b)
print(c)
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
[[ 6]
 [12]]
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [13]:
a = np.array([1,2,3])
b = a
c = a[:]
d = np.copy(a)
print(b is a,c is a,d is a)
d[0] = 10
print(a,d)
c[0] = 100
print(a,c)

True False False
[1 2 3] [10  2  3]
[100   2   3] [100   2   3]


In [14]:
import numpy as np
import numpy.linalg as lg
a1 = np.array([[1,2,3],[4,5,6],[5,4,5]])
a5 = np.array([[1,5,4],[3,4,7],[7,5,6]])
print(a1+a5)
print(a1-a5)
print(a1/a5)
print(a1 % a5)
print(a1 ** a5)

[[ 2  7  7]
 [ 7  9 13]
 [12  9 11]]
[[ 0 -3 -1]
 [ 1  1 -1]
 [-2 -1 -1]]
[[1.         0.4        0.75      ]
 [1.33333333 1.25       0.85714286]
 [0.71428571 0.8        0.83333333]]
[[0 2 3]
 [1 1 6]
 [5 4 5]]
[[     1     32     81]
 [    64    625 279936]
 [ 78125   1024  15625]]


In [15]:
arr = np.array([[1,2,3],[3,6,7],[4,2,9]])
print('计算3x3方阵的特征根和特征向量：\n',arr)
print('求解结果为：\n',np.linalg.eig(arr))

计算3x3方阵的特征根和特征向量：
 [[1 2 3]
 [3 6 7]
 [4 2 9]]
求解结果为：
 (array([13.10729668, -0.28784952,  3.18055283]), array([[-0.2754406 , -0.91822111, -0.20009533],
       [-0.73107224, -0.00282187, -0.87610721],
       [-0.62423221,  0.39605812,  0.43863199]]))


In [16]:
X = np.array([160,165,157,122,159,126,160,162,121])
MIN = np.min(X)
MAX = np.max(X)
print(MIN)
print(MAX)
a = np.array([[3,2,5],[7,4,3],[2,4,9]])
print('数组是：')
print(a)
print('\n')
print('调用amin()函数')
print(np.amin(a,1))
print('\n')
print('再次调用amin（）函数：')
print(np.amin(a,0))
print('\n')
print('调用amax()函数：')
print(np.amax(a))
print('\n')
print('再次调用amax()函数')
print(np.amax(a,axis=0))

121
165
数组是：
[[3 2 5]
 [7 4 3]
 [2 4 9]]


调用amin()函数
[2 3 2]


再次调用amin（）函数：
[2 2 3]


调用amax()函数：
9


再次调用amax()函数
[7 4 9]


In [17]:
a = np.array([[3,2,5],[7,4,3],[2,4,9]])
print('数组是：')
print(a)
print('\n')
print('调用ptp()函数：')
print(np.ptp(a))
print('\n')
print('沿轴1调用ptp()函数：')
print(np.ptp(a,axis=1))
print('\n')
print('沿轴0调用ptp()函数:')
print(np.ptp(a,axis=0))

数组是：
[[3 2 5]
 [7 4 3]
 [2 4 9]]


调用ptp()函数：
7


沿轴1调用ptp()函数：
[3 4 7]


沿轴0调用ptp()函数:
[5 2 6]


In [1]:
#习题

In [2]:
import numpy as np

In [3]:
from numpy.linalg import solve

In [4]:
a = np.mat([[1,2,4],[4,3,-7],[8,4,2]])

In [5]:
b = np.mat([7,89,23]).T

In [6]:
x = solve(a,b)
print(x)

[[-5.61904762]
 [20.54761905]
 [-7.11904762]]


In [8]:
c = np.array([[3,6,7],[2,5,4],[1,8,9]])

In [9]:
print(c.T)

[[3 2 1]
 [6 5 8]
 [7 4 9]]


In [11]:
import numpy.linalg as lg
print(lg.inv(c))

[[ 0.40625  0.0625  -0.34375]
 [-0.4375   0.625    0.0625 ]
 [ 0.34375 -0.5625   0.09375]]
